name: node-websockets

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  ws1:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=4001
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis

  ws2:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=4002
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis

  ws3:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=4003
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ws1
      - ws2
      - ws3

volumes:
  caddy_data:
  caddy_config:
